# Generated by Django 4.2.30 on 2026-04-24 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名')),
                ('isbn', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='ISBN')),
                ('author', models.CharField(max_length=200, verbose_name='作者')),
                ('publisher', models.CharField(blank=True, default='', max_length=200, verbose_name='出版社')),
                ('description', models.TextField(blank=True, default='', verbose_name='简介')),
                ('total_copies', models.PositiveIntegerField(default=1, verbose_name='总册数')),
                ('available_copies', models.PositiveIntegerField(default=1, verbose_name='在架册数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='分类名')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowed_at', models.DateTimeField(auto_now_add=True, verbose_name='借出时间')),
                ('due_at', models.DateTimeField(verbose_name='应还时间')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='实际归还')),
                ('status', models.CharField(choices=[('borrowed', '在借'), ('returned', '已归还')], default='borrowed', max_length=20, verbose_name='状态')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_records', to='books.book', verbose_name='图书')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrows', to=settings.AUTH_USER_MODEL, verbose_name='读者')),
            ],
            options={
                'verbose_name': '借阅记录',
                'verbose_name_plural': '借阅记录',
                'ordering': ('-borrowed_at',),
            },
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='books', to='books.category', verbose_name='分类'),
        ),
    ]
