# Generated by Django 4.2.30 on 2026-05-06 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0007_sitesettings"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="borrowrecord",
            constraint=models.UniqueConstraint(
                condition=models.Q(status="borrowed"),
                fields=("user", "book"),
                name="books_borrowrecord_active_user_book_uniq",
            ),
        ),
    ]
